import { createSlice } from "@reduxjs/toolkit";

const INITIAL_STATE = [
  { id: 1, code: "AF", country: "Afghanistan" },
  { id: 2, code: "AX", country: "Åland Islands" },
  { id: 3, code: "AL", country: "Albania" },
  { id: 4, code: "DZ", country: "Algeria" },
  { id: 5, code: "AS", country: "American Samoa" },
  { id: 6, code: "AD", country: "Andorra" },
  { id: 7, code: "AO", country: "Angola" },
  { id: 8, code: "AI", country: "Anguilla" },
  { id: 9, code: "AQ", country: "Antarctica" },
  { id: 10, code: "AG", country: "Antigua and Barbuda" },
  { id: 11, code: "AR", country: "Argentina" },
  { id: 12, code: "AM", country: "Armenia" },
  { id: 13, code: "AW", country: "Aruba" },
  { id: 14, code: "AU", country: "Australia" },
  { id: 15, code: "AT", country: "Austria" },
  { id: 16, code: "AZ", country: "Azerbaijan" },
  { id: 17, code: "BS", country: "Bahamas" },
  { id: 18, code: "BH", country: "Bahrain" },
  { id: 19, code: "BD", country: "Bangladesh" },
  { id: 20, code: "BB", country: "Barbados" },
  { id: 21, code: "BY", country: "Belarus" },
  { id: 22, code: "BE", country: "Belgium" },
  { id: 23, code: "BZ", country: "Belize" },
  { id: 24, code: "BJ", country: "Benin" },
  { id: 25, code: "BM", country: "Bermuda" },
  { id: 26, code: "BT", country: "Bhutan" },
  { id: 27, code: "BO", country: "Bolivia (Plurinational State of)" },
  { id: 28, code: "BQ", country: "Bonaire, Sint Eustatius and Saba" },
  { id: 29, code: "BA", country: "Bosnia and Herzegovina" },
  { id: 30, code: "BW", country: "Botswana" },
  { id: 31, code: "BV", country: "Bouvet Island" },
  { id: 32, code: "BR", country: "Brazil" },
  { id: 33, code: "IO", country: "British Indian Ocean Territory" },
  { id: 34, code: "BN", country: "Brunei Darussalam" },
  { id: 35, code: "BG", country: "Bulgaria" },
  { id: 36, code: "BF", country: "Burkina Faso" },
  { id: 37, code: "BI", country: "Burundi" },
  { id: 38, code: "CV", country: "Cabo Verde" },
  { id: 39, code: "KH", country: "Cambodia" },
  { id: 40, code: "CM", country: "Cameroon" },
  { id: 41, code: "CA", country: "Canada" },
  { id: 42, code: "KY", country: "Cayman Islands" },
  { id: 43, code: "CF", country: "Central African Republic" },
  { id: 44, code: "TD", country: "Chad" },
  { id: 45, code: "CL", country: "Chile" },
  { id: 46, code: "CN", country: "China" },
  { id: 47, code: "CX", country: "Christmas Island" },
  { id: 48, code: "CC", country: "Cocos (Keeling) Islands" },
  { id: 49, code: "CO", country: "Colombia" },
  { id: 50, code: "KM", country: "Comoros" },
  { id: 51, code: "CG", country: "Congo" },
  { id: 52, code: "CD", country: "Congo (Democratic Republic of the)" },
  { id: 53, code: "CK", country: "Cook Islands" },
  { id: 54, code: "CR", country: "Costa Rica" },
  { id: 55, code: "CI", country: "Côte d'Ivoire" },
  { id: 56, code: "HR", country: "Croatia" },
  { id: 57, code: "CU", country: "Cuba" },
  { id: 58, code: "CW", country: "Curaçao" },
  { id: 59, code: "CY", country: "Cyprus" },
  { id: 60, code: "CZ", country: "Czechia" },
  { id: 61, code: "DK", country: "Denmark" },
  { id: 62, code: "DJ", country: "Djibouti" },
  { id: 63, code: "DM", country: "Dominica" },
  { id: 64, code: "DO", country: "Dominican Republic" },
  { id: 65, code: "EC", country: "Ecuador" },
  { id: 66, code: "EG", country: "Egypt" },
  { id: 67, code: "SV", country: "El Salvador" },
  { id: 68, code: "GQ", country: "Equatorial Guinea" },
  { id: 69, code: "ER", country: "Eritrea" },
  { id: 70, code: "EE", country: "Estonia" },
  { id: 71, code: "ET", country: "Ethiopia" },
  { id: 72, code: "FK", country: "Falkland Islands (Malvinas)" },
  { id: 73, code: "FO", country: "Faroe Islands" },
  { id: 74, code: "FJ", country: "Fiji" },
  { id: 75, code: "FI", country: "Finland" },
  { id: 76, code: "FR", country: "France" },
  { id: 77, code: "GF", country: "French Guiana" },
  { id: 78, code: "PF", country: "French Polynesia" },
  { id: 79, code: "TF", country: "French Southern Territories" },
  { id: 80, code: "GA", country: "Gabon" },
  { id: 81, code: "GM", country: "Gambia" },
  { id: 82, code: "GE", country: "Georgia" },
  { id: 83, code: "DE", country: "Germany" },
  { id: 84, code: "GH", country: "Ghana" },
  { id: 85, code: "GI", country: "Gibraltar" },
  { id: 86, code: "GR", country: "Greece" },
  { id: 87, code: "GL", country: "Greenland" },
  { id: 88, code: "GD", country: "Grenada" },
  { id: 89, code: "GP", country: "Guadeloupe" },
  { id: 90, code: "GU", country: "Guam" },
  { id: 91, code: "GT", country: "Guatemala" },
  { id: 92, code: "GG", country: "Guernsey" },
  { id: 93, code: "GN", country: "Guinea" },
  { id: 94, code: "GW", country: "Guinea-Bissau" },
  { id: 95, code: "GY", country: "Guyana" },
  { id: 96, code: "HT", country: "Haiti" },
  { id: 97, code: "HM", country: "Heard Island and McDonald Islands" },
  { id: 98, code: "VA", country: "Holy See" },
  { id: 99, code: "HN", country: "Honduras" },
  { id: 100, code: "HK", country: "Hong Kong" },
  { id: 101, code: "HU", country: "Hungary" },
  { id: 102, code: "IS", country: "Iceland" },
  { id: 103, code: "IN", country: "India" },
  { id: 104, code: "ID", country: "Indonesia" },
  { id: 105, code: "IR", country: "Iran (Islamic Republic of)" },
  { id: 106, code: "IQ", country: "Iraq" },
  { id: 107, code: "IE", country: "Ireland" },
  { id: 108, code: "IM", country: "Isle of Man" },
  { id: 109, code: "IL", country: "Israel" },
  { id: 110, code: "IT", country: "Italy" },
  { id: 111, code: "JM", country: "Jamaica" },
  { id: 112, code: "JP", country: "Japan" },
  { id: 113, code: "JE", country: "Jersey" },
  { id: 114, code: "JO", country: "Jordan" },
  { id: 115, code: "KZ", country: "Kazakhstan" },
  { id: 116, code: "KE", country: "Kenya" },
  { id: 117, code: "KI", country: "Kiribati" },
  { id: 118, code: "KP", country: "Korea (Democratic People's Republic of)" },
  { id: 119, code: "KR", country: "Korea (Republic of)" },
  { id: 120, code: "KW", country: "Kuwait" },
  { id: 121, code: "KG", country: "Kyrgyzstan" },
  { id: 122, code: "LA", country: "Lao People's Democratic Republic" },
  { id: 123, code: "LV", country: "Latvia" },
  { id: 124, code: "LB", country: "Lebanon" },
  { id: 125, code: "LS", country: "Lesotho" },
  { id: 126, code: "LR", country: "Liberia" },
  { id: 127, code: "LY", country: "Libya" },
  { id: 128, code: "LI", country: "Liechtenstein" },
  { id: 129, code: "LT", country: "Lithuania" },
  { id: 130, code: "LU", country: "Luxembourg" },
  { id: 131, code: "MO", country: "Macao" },
  {
    id: 132,
    code: "MK",
    country: "Macedonia (the former Yugoslav Republic of)",
  },
  { id: 133, code: "MG", country: "Madagascar" },
  { id: 134, code: "MW", country: "Malawi" },
  { id: 135, code: "MY", country: "Malaysia" },
  { id: 136, code: "MV", country: "Maldives" },
  { id: 137, code: "ML", country: "Mali" },
  { id: 138, code: "MT", country: "Malta" },
  { id: 139, code: "MH", country: "Marshall Islands" },
  { id: 140, code: "MQ", country: "Martinique" },
  { id: 141, code: "MR", country: "Mauritania" },
  { id: 142, code: "MU", country: "Mauritius" },
  { id: 143, code: "YT", country: "Mayotte" },
  { id: 144, code: "MX", country: "Mexico" },
  { id: 145, code: "FM", country: "Micronesia (Federated States of)" },
  { id: 146, code: "MD", country: "Moldova (Republic of)" },
  { id: 147, code: "MC", country: "Monaco" },
  { id: 148, code: "MN", country: "Mongolia" },
  { id: 149, code: "ME", country: "Montenegro" },
  { id: 150, code: "MS", country: "Montserrat" },
  { id: 151, code: "MA", country: "Morocco" },
  { id: 152, code: "MZ", country: "Mozambique" },
  { id: 153, code: "MM", country: "Myanmar" },
  { id: 154, code: "NA", country: "Namibia" },
  { id: 155, code: "NR", country: "Nauru" },
  { id: 156, code: "NP", country: "Nepal" },
  { id: 157, code: "NL", country: "Netherlands" },
  { id: 158, code: "NC", country: "New Caledonia" },
  { id: 159, code: "NZ", country: "New Zealand" },
  { id: 160, code: "NI", country: "Nicaragua" },
  { id: 161, code: "NE", country: "Niger" },
  { id: 162, code: "NG", country: "Nigeria" },
  { id: 163, code: "NU", country: "Niue" },
  { id: 164, code: "NF", country: "Norfolk Island" },
  { id: 165, code: "MP", country: "Northern Mariana Islands" },
  { id: 166, code: "NO", country: "Norway" },
  { id: 167, code: "OM", country: "Oman" },
  { id: 168, code: "PK", country: "Pakistan" },
  { id: 169, code: "PW", country: "Palau" },
  { id: 170, code: "PS", country: "Palestine, State of" },
  { id: 171, code: "PA", country: "Panama" },
  { id: 172, code: "PG", country: "Papua New Guinea" },
  { id: 173, code: "PY", country: "Paraguay" },
  { id: 174, code: "PE", country: "Peru" },
  { id: 175, code: "PH", country: "Philippines" },
  { id: 176, code: "PN", country: "Pitcairn" },
  { id: 177, code: "PL", country: "Poland" },
  { id: 178, code: "PT", country: "Portugal" },
  { id: 179, code: "PR", country: "Puerto Rico" },
  { id: 180, code: "QA", country: "Qatar" },
  { id: 181, code: "RE", country: "Réunion" },
  { id: 182, code: "RO", country: "Romania" },
  { id: 183, code: "RU", country: "Russian Federation" },
  { id: 184, code: "RW", country: "Rwanda" },
  { id: 185, code: "BL", country: "Saint Barthélemy" },
  {
    id: 186,
    code: "SH",
    country: "Saint Helena, Ascension and Tristan da Cunha",
  },
  { id: 187, code: "KN", country: "Saint Kitts and Nevis" },
  { id: 188, code: "LC", country: "Saint Lucia" },
  { id: 189, code: "MF", country: "Saint Martin (French part)" },
  { id: 190, code: "PM", country: "Saint Pierre and Miquelon" },
  { id: 191, code: "VC", country: "Saint Vincent and the Grenadines" },
  { id: 192, code: "WS", country: "Samoa" },
  { id: 193, code: "SM", country: "San Marino" },
  { id: 194, code: "ST", country: "Sao Tome and Principe" },
  { id: 195, code: "SA", country: "Saudi Arabia" },
  { id: 196, code: "SN", country: "Senegal" },
  { id: 197, code: "RS", country: "Serbia" },
  { id: 198, code: "SC", country: "Seychelles" },
  { id: 199, code: "SL", country: "Sierra Leone" },
  { id: 200, code: "SG", country: "Singapore" },
  { id: 201, code: "SX", country: "Sint Maarten (Dutch part)" },
  { id: 202, code: "SK", country: "Slovakia" },
  { id: 203, code: "SI", country: "Slovenia" },
  { id: 204, code: "SB", country: "Solomon Islands" },
  { id: 205, code: "SO", country: "Somalia" },
  { id: 206, code: "ZA", country: "South Africa" },
  {
    id: 207,
    code: "GS",
    country: "South Georgia and the South Sandwich Islands",
  },
  { id: 208, code: "SS", country: "South Sudan" },
  { id: 209, code: "ES", country: "Spain" },
  { id: 210, code: "LK", country: "Sri Lanka" },
  { id: 211, code: "SD", country: "Sudan" },
  { id: 212, code: "SR", country: "Suriname" },
  { id: 213, code: "SJ", country: "Svalbard and Jan Mayen" },
  { id: 214, code: "SZ", country: "Swaziland" },
  { id: 215, code: "SE", country: "Sweden" },
  { id: 216, code: "CH", country: "Switzerland" },
  { id: 217, code: "SY", country: "Syrian Arab Republic" },
  { id: 218, code: "TW", country: "Taiwan, Province of China[a]" },
  { id: 219, code: "TJ", country: "Tajikistan" },
  { id: 220, code: "TZ", country: "Tanzania, United Republic of" },
  { id: 221, code: "TH", country: "Thailand" },
  { id: 222, code: "TL", country: "Timor-Leste" },
  { id: 223, code: "TG", country: "Togo" },
  { id: 224, code: "TK", country: "Tokelau" },
  { id: 225, code: "TO", country: "Tonga" },
  { id: 226, code: "TT", country: "Trinidad and Tobago" },
  { id: 227, code: "TN", country: "Tunisia" },
  { id: 228, code: "TR", country: "Turkey" },
  { id: 229, code: "TM", country: "Turkmenistan" },
  { id: 230, code: "TC", country: "Turks and Caicos Islands" },
  { id: 231, code: "TV", country: "Tuvalu" },
  { id: 232, code: "UG", country: "Uganda" },
  { id: 233, code: "UA", country: "Ukraine" },
  { id: 234, code: "AE", country: "United Arab Emirates" },
  {
    id: 235,
    code: "GB",
    country: "United Kingdom of Great Britain and Northern Ireland",
  },
  { id: 236, code: "US", country: "United States of America" },
  { id: 237, code: "UM", country: "United States Minor Outlying Islands" },
  { id: 238, code: "UY", country: "Uruguay" },
  { id: 239, code: "UZ", country: "Uzbekistan" },
  { id: 240, code: "VU", country: "Vanuatu" },
  { id: 241, code: "VE", country: "Venezuela (Bolivarian Republic of)" },
  { id: 242, code: "VN", country: "Viet Nam" },
  { id: 243, code: "VG", country: "Virgin Islands (British)" },
  { id: 244, code: "VI", country: "Virgin Islands (U.S.)" },
  { id: 245, code: "WF", country: "Wallis and Futuna" },
  { id: 246, code: "EH", country: "Western Sahara" },
  { id: 247, code: "YE", country: "Yemen" },
  { id: 248, code: "ZM", country: "Zambia" },
  { id: 249, code: "ZW", country: "Zimbabwe" },
];

const locationsSlice = createSlice({
  name: "locations",
  initialState: INITIAL_STATE,
  reducers: {},
});

export const locationsReducer = locationsSlice.reducer;
